#!/usr/bin/env bash

# TODO: investigate why "sudo dpkg --set-selections" fails.
pkgs+=(autossh ssh-import-id)
pkgs+=(bash-completion)
pkgs+=(ttf-bitstream-vera)
pkgs+=(ccache)
pkgs+=(cheese)
pkgs+=(cscope doxygen mscgen)
pkgs+=(curl wget)
pkgs+=(dmenu)
pkgs+=(dos2unix)
pkgs+=(espeak)
pkgs+=(g++)
pkgs+=(gcc)
pkgs+=(gdb)
pkgs+=(gimp)
pkgs+=(git git-gui gitk github-cli git-svn)
pkgs+=(gnome-specimen)
pkgs+=(googlecl)
pkgs+=(gparted unetbootin)
pkgs+=(graphviz)
pkgs+=(htop)
pkgs+=(ia32-libs)
pkgs+=(idle ipython)
pkgs+=(imagemagick)
pkgs+=(iodine)
pkgs+=(iperf)
pkgs+=(lrzsz)
pkgs+=(lsb-release)
pkgs+=(lshw lspci lsscsi)
pkgs+=(lsof)
pkgs+=(lynx)
pkgs+=(make)
pkgs+=(meld colordiff)
pkgs+=(moreutils)
pkgs+=(mtpaint)
pkgs+=(rar unrar p7zip p7zip-rar)
pkgs+=(pbuilder)
pkgs+=(playonlinux)
pkgs+=(python-beautifulsoup)
pkgs+=(qemu qemu-kvm qemubuilder)
pkgs+=(rsync)
pkgs+=(screen tmux)
#pkgs+=(skype)
pkgs+=(sg3-utils)
pkgs+=(sqlitebrowser)
pkgs+=(telnet)
pkgs+=(touchegg)
pkgs+=(usbutils)
pkgs+=(vim-gnome)
pkgs+=(virtualbox virtualbox-guest-additions-iso)
pkgs+=(vlc)
pkgs+=(winbind)
pkgs+=(xclip)
pkgs+=(xdotool wmctrl)
pkgs+=(xmonad gnome-panel)

# eagle logic
# openscad inkscape blender

sudo apt-get install "${pkgs[@]}"
