#!/usr/bin/env bash
sudo dpkg --set-selections <<EOF
# eagle logic
# openscad inkscape blender	
autossh						install
bash-completion					install
binutils					install
build-essential					install
bzip2						install
bzr						install
ccache						install
colordiff					install
coreutils					install
cron						install
cscope						install
curl						install
espeak						install
g++						install
gcc						install
gdb						install
gimp						install
git						install
git-gui						install
github-cli					install
gitk						install
gnome-specimen					install
gparted						install
graphviz					install
gzip						install
idle						install
imagemagick					install
iodine						install
iperf						install
ipython						install
lsb-release					install
lshw						install
lsof						install
lynx						install
make						install
meld						install
moreutils					install
p7zip						install
pbuilder					install
python-beautifulsoup				install
qemu						install
qemubuilder					install
rar						install
rsync						install
screen						install
skype						install
sqlitebrowser					install
ssh-import-id					install
telnet						install
unetbootin					install
unrar						install
unzip						install
usbutils					install
vim-gnome					install
virtualbox					install
vlc						install
wget						install
winbind						install
wmctrl						install
xclip						install
xdotool						install
zip						install
EOF
sudo apt-get dselect-upgrade
