Vagrant.configure('2') do |config|
  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--memory', '4096']
  end
  config.vm.network 'forwarded_port', guest: 8080, host: 8080
end
